### ISSUE TITLE
Calling a BAML function in a celery worker on darwin-arm64 reliably triggers a SIGSEGV

### ISSUE THREAD

**Issue by sxlijin** [BoundaryML/baml#778]
Repro instructions on my machine

Log message: https://gist.github.com/sxlijin/5575618890e39386c5494deb1051974f

**Comment by hellovai** [comment]
This is resolved now thanks to #803  (confirmed and tested that a crash NEVER happens when using celery with sync interfaces).

The bug was caused by UB of async futures mixing poorly with FFI boundaries and pickling from multiprocessing. 

As long as a user uses the new sync interface exposed by baml, crashes should not happen.
